import { query } from "../db";

export async function updateSettings(data: FormData): Promise<void> {
  const s    = (k: string) => (data.get(k) as string | null)?.trim() || null;
  const raw  = (k: string) => (data.get(k) as string | null) || null;
  const b    = (k: string) => data.get(k) === "on";
  const iopt = (k: string) => { const v = data.get(k) as string; return v?.trim() ? parseInt(v) || null : null; };
  const idef = (k: string, def = 0) => { const v = data.get(k) as string; return v?.trim() ? parseInt(v) ?? def : def; };

  await query(
    `UPDATE Settings SET
       SiteName = @site_name, SiteNameAB = @site_name_ab, DomainName = @domain_name,
       DefaultImages = @default_images,
       Logo_desktop = @logo_desktop, Logo_mobile = @logo_mobile, Logo_print = @logo_print,
       Logo_desktop_stickey_width = @logo_sticky_w, Logo_desktop_stickey_height = @logo_sticky_h,
       Logo_desktop_stickey_data_width = @logo_sticky_data_w, Logo_desktop_stickey_data_height = @logo_sticky_data_h,
       Phone = @phone, Phone2 = @phone2, Phone3 = @phone3, Phone4 = @phone4, Phone5 = @phone5,
       Address1 = @address1, Address2 = @address2,
       City = @city, State = @state, Postalcode = @postalcode, HomeCountry = @home_country,
       MerchantEmail = @merchant_email, StoreEmail = @merchant_email, Webmaster = @webmaster,
       Merchant = @merchant, GoogleMapEmbed = @google_map_embed,
       Email_Server = @email_server, Email_User = @email_user, Email_Pass = @email_pass,
       Email_Port = @email_port, Email_useSSL = @email_use_ssl, Email_useTLS = @email_use_tls,
       use_mailingList = @use_mailing_list,
       Locale = @locale, MoneyUnit = @money_unit, WeightUnit = @weight_unit,
       SizeUnit = @size_unit, TimeOffset = @time_offset, ExcludeIP = @exclude_ip,
       metatitle = @metatitle, metadescription = @metadescription,
       Keywords = @keywords, og_image = @og_image,
       googleapikey = @googleapikey, googletrackingcode = @googletrackingcode,
       google_site_verification = @google_site_verification,
       GoogleClientID = @google_client_id, FacebookAppID = @facebook_app_id,
       AppleAppID = @apple_app_id,
       pinteresttagid = @pinteresttagid,
       pinterest_site_verification = @pinterest_site_verification,
       turnstile_site_key = @turnstile_site_key, turnstile_secret_key = @turnstile_secret_key,
       showcaptcha = @showcaptcha, captchaSiteKey = @captcha_site_key,
       captchaSiteSecret = @captcha_site_secret,
       Login_ShowOneTimeCode = @login_one_time_code,
       Algolia_ShowInstantSearch = @algolia_instant_search,
       Algolia_ShowAutocomplete = @algolia_autocomplete,
       Algolia_Application_ID = @algolia_app_id,
       Algolia_Search_API_Key = @algolia_search_key,
       Algolia_site_verification = @algolia_verification,
       Algolia_Product_Index = @algolia_product_index,
       Algolia_Category_Index = @algolia_category_index,
       Algolia_Article_Index = @algolia_article_index,
       Algolia_Suggestion_Index = @algolia_suggestion_index,
       Category_Image_Height = @cat_image_height,
       category_sm_image_width = @cat_sm_w, category_sm_image_height = @cat_sm_h,
       category_lg_image_width = @cat_lg_w, category_lg_image_height = @cat_lg_h,
       Image_quality = @image_quality,
       Maxfeatures = @maxfeatures, DoNotDspFeaturesInOffCats = @feat_off_cats,
       InvLevel = @inv_level, UseInvTab = @use_inv_tab,
       ShowInStock = @show_in_stock, OutofStock = @out_of_stock,
       ShowRetail = @show_retail, ItemSort = @item_sort,
       ShowProductSubscriptions = @show_subscriptions,
       OrderButtonText = @order_button_text,
       RegistryButtonText = @registry_button_text,
       WishlistButtonText = @wishlist_button_text,
       RelatedProducts_title = @related_products_title,
       DoNotDspProdsInOffCats = @prods_off_cats, Maxprods = @maxprods,
       Product_show_Details = @prod_show_details,
       Product_show_shortDesc = @prod_show_short_desc,
       Product_show_orderBox = @prod_show_order_box,
       Product_show_ratings = @prod_show_ratings,
       Product_show_Icons = @prod_show_icons,
       Product_show_sku = @prod_show_sku,
       Product_show_customFields = @prod_show_custom_fields,
       Product_Image_Height = @prod_image_height,
       th_image_width = @th_w, th_image_height = @th_h,
       sm_image_width = @sm_w, sm_image_height = @sm_h,
       md_image_width = @md_w, md_image_height = @md_h,
       lg_image_width = @lg_w, lg_image_height = @lg_h,
       Mimetypes = @mimetypes, AllowExtensions = @allow_extensions,
       Alert_Display = @alert_display, alert_message = @alert_message
     WHERE SettingID = 1`,
    {
      site_name:                s("site_name"),
      site_name_ab:             s("site_name_ab"),
      domain_name:              s("domain_name"),
      default_images:           s("default_images"),
      logo_desktop:             s("logo_desktop"),
      logo_mobile:              s("logo_mobile"),
      logo_print:               s("logo_print"),
      logo_sticky_w:            iopt("logo_sticky_w"),
      logo_sticky_h:            iopt("logo_sticky_h"),
      logo_sticky_data_w:       iopt("logo_sticky_data_w"),
      logo_sticky_data_h:       iopt("logo_sticky_data_h"),
      phone:                    s("phone"),
      phone2:                   s("phone2"),
      phone3:                   s("phone3"),
      phone4:                   s("phone4"),
      phone5:                   s("phone5"),
      address1:                 s("address1"),
      address2:                 s("address2"),
      city:                     s("city"),
      state:                    s("state"),
      postalcode:               s("postalcode"),
      home_country:             s("home_country"),
      merchant_email:           s("merchant_email"),
      webmaster:                s("webmaster"),
      merchant:                 raw("merchant"),
      google_map_embed:         raw("google_map_embed"),
      email_server:             s("email_server"),
      email_user:               s("email_user"),
      email_pass:               s("email_pass"),
      email_port:               iopt("email_port"),
      email_use_ssl:            b("email_use_ssl"),
      email_use_tls:            b("email_use_tls"),
      use_mailing_list:         idef("use_mailing_list"),
      locale:                   s("locale"),
      money_unit:               s("money_unit"),
      weight_unit:              s("weight_unit"),
      size_unit:                s("size_unit"),
      time_offset:              idef("time_offset"),
      exclude_ip:               s("exclude_ip"),
      metatitle:                s("metatitle"),
      metadescription:          s("metadescription"),
      keywords:                 s("keywords"),
      og_image:                 s("og_image"),
      googleapikey:             s("googleapikey"),
      googletrackingcode:       s("googletrackingcode"),
      google_site_verification: s("google_site_verification"),
      google_client_id:         s("google_client_id"),
      facebook_app_id:          s("facebook_app_id"),
      apple_app_id:             s("apple_app_id"),
      pinteresttagid:           s("pinteresttagid"),
      pinterest_site_verification: s("pinterest_site_verification"),
      turnstile_site_key:       s("turnstile_site_key"),
      turnstile_secret_key:     s("turnstile_secret_key"),
      showcaptcha:              b("showcaptcha"),
      captcha_site_key:         s("captcha_site_key"),
      captcha_site_secret:      s("captcha_site_secret"),
      login_one_time_code:      b("login_one_time_code"),
      algolia_instant_search:   b("algolia_instant_search"),
      algolia_autocomplete:     b("algolia_autocomplete"),
      algolia_app_id:           s("algolia_app_id"),
      algolia_search_key:       s("algolia_search_key"),
      algolia_verification:     s("algolia_verification"),
      algolia_product_index:    s("algolia_product_index"),
      algolia_category_index:   s("algolia_category_index"),
      algolia_article_index:    s("algolia_article_index"),
      algolia_suggestion_index: s("algolia_suggestion_index"),
      cat_image_height:         iopt("cat_image_height"),
      cat_sm_w:                 iopt("cat_sm_w"),
      cat_sm_h:                 iopt("cat_sm_h"),
      cat_lg_w:                 iopt("cat_lg_w"),
      cat_lg_h:                 iopt("cat_lg_h"),
      image_quality:            iopt("image_quality"),
      maxfeatures:              idef("maxfeatures", 9999),
      feat_off_cats:            b("feat_off_cats"),
      inv_level:                s("inv_level"),
      use_inv_tab:              b("use_inv_tab"),
      show_in_stock:            b("show_in_stock"),
      out_of_stock:             b("out_of_stock"),
      show_retail:              b("show_retail"),
      item_sort:                s("item_sort"),
      show_subscriptions:       b("show_subscriptions"),
      order_button_text:        s("order_button_text"),
      registry_button_text:     s("registry_button_text"),
      wishlist_button_text:     s("wishlist_button_text"),
      related_products_title:   s("related_products_title"),
      prods_off_cats:           b("prods_off_cats"),
      maxprods:                 idef("maxprods", 9999),
      prod_show_details:        idef("prod_show_details", 1),
      prod_show_short_desc:     idef("prod_show_short_desc", 1),
      prod_show_order_box:      idef("prod_show_order_box", 1),
      prod_show_ratings:        idef("prod_show_ratings", 1),
      prod_show_icons:          idef("prod_show_icons", 1),
      prod_show_sku:            idef("prod_show_sku", 1),
      prod_show_custom_fields:  idef("prod_show_custom_fields", 1),
      prod_image_height:        iopt("prod_image_height"),
      th_w:                     idef("th_w", 1),
      th_h:                     idef("th_h", 1),
      sm_w:                     idef("sm_w", 1),
      sm_h:                     idef("sm_h", 1),
      md_w:                     idef("md_w", 1),
      md_h:                     idef("md_h", 1),
      lg_w:                     idef("lg_w", 1),
      lg_h:                     idef("lg_h", 1),
      mimetypes:                s("mimetypes"),
      allow_extensions:         s("allow_extensions"),
      alert_display:            b("alert_display"),
      alert_message:            raw("alert_message"),
    }
  );
}
