import { query } from "../db";

export async function updateSettings(data: FormData): Promise<void> {
  const s = (k: string) => (data.get(k) as string | null)?.trim() || null;
  const raw = (k: string) => (data.get(k) as string | null) || null;
  const b = (k: string) => data.get(k) === "on";
  const iopt = (k: string) => { const v = data.get(k) as string; return v?.trim() ? parseInt(v) || null : null; };

  await query(
    `UPDATE Settings SET
       SiteName = @site_name, SiteNameAB = @site_name_ab, DomainName = @domain_name,
       DefaultImages = @default_images,
       Logo_desktop = @logo_desktop, Logo_mobile = @logo_mobile, Logo_print = @logo_print,
       Phone = @phone, Phone2 = @phone2, Phone3 = @phone3, Phone4 = @phone4, Phone5 = @phone5,
       Address1 = @address1, Address2 = @address2,
       City = @city, State = @state, Postalcode = @postalcode, HomeCountry = @home_country,
       Email = @email, MerchantEmail = @merchant_email, Webmaster = @webmaster,
       Merchant = @merchant, GoogleMapEmbed = @google_map_embed,
       Email_Server = @email_server, Email_User = @email_user, Email_Pass = @email_pass,
       Email_Port = @email_port, Email_useSSL = @email_use_ssl, Email_useTLS = @email_use_tls,
       metatitle = @metatitle, metadescription = @metadescription,
       Keywords = @keywords, og_image = @og_image,
       googleapikey = @googleapikey, googletrackingcode = @googletrackingcode,
       google_site_verification = @google_site_verification,
       GoogleClientID = @google_client_id, FacebookAppID = @facebook_app_id,
       AppleAppID = @apple_app_id,
       pinteresttagid = @pinteresttagid,
       pinterest_site_verification = @pinterest_site_verification,
       turnstile_site_key = @turnstile_site_key, turnstile_secret_key = @turnstile_secret_key,
       showcaptcha = @showcaptcha, captchaSiteKey = @captcha_site_key,
       captchaSiteSecret = @captcha_site_secret,
       Algolia_ShowInstantSearch = @algolia_instant_search,
       Algolia_ShowAutocomplete = @algolia_autocomplete,
       Algolia_Application_ID = @algolia_app_id,
       Algolia_Search_API_Key = @algolia_search_key,
       Algolia_site_verification = @algolia_verification,
       Algolia_Product_Index = @algolia_product_index,
       Algolia_Category_Index = @algolia_category_index,
       Algolia_Article_Index = @algolia_article_index,
       Algolia_Suggestion_Index = @algolia_suggestion_index,
       InvLevel = @inv_level, ShowInStock = @show_in_stock,
       OutofStock = @out_of_stock, ShowRetail = @show_retail,
       OrderButtonText = @order_button_text,
       Alert_Display = @alert_display, alert_message = @alert_message
     WHERE SettingID = 1`,
    {
      site_name:                s("site_name"),
      site_name_ab:             s("site_name_ab"),
      domain_name:              s("domain_name"),
      default_images:           s("default_images"),
      logo_desktop:             s("logo_desktop"),
      logo_mobile:              s("logo_mobile"),
      logo_print:               s("logo_print"),
      phone:                    s("phone"),
      phone2:                   s("phone2"),
      phone3:                   s("phone3"),
      phone4:                   s("phone4"),
      phone5:                   s("phone5"),
      address1:                 s("address1"),
      address2:                 s("address2"),
      city:                     s("city"),
      state:                    s("state"),
      postalcode:               s("postalcode"),
      home_country:             s("home_country"),
      email:                    s("email"),
      merchant_email:           s("merchant_email"),
      webmaster:                s("webmaster"),
      merchant:                 raw("merchant"),
      google_map_embed:         raw("google_map_embed"),
      email_server:             s("email_server"),
      email_user:               s("email_user"),
      email_pass:               s("email_pass"),
      email_port:               iopt("email_port"),
      email_use_ssl:            b("email_use_ssl"),
      email_use_tls:            b("email_use_tls"),
      metatitle:                s("metatitle"),
      metadescription:          s("metadescription"),
      keywords:                 s("keywords"),
      og_image:                 s("og_image"),
      googleapikey:             s("googleapikey"),
      googletrackingcode:       s("googletrackingcode"),
      google_site_verification: s("google_site_verification"),
      google_client_id:         s("google_client_id"),
      facebook_app_id:          s("facebook_app_id"),
      apple_app_id:             s("apple_app_id"),
      pinteresttagid:           s("pinteresttagid"),
      pinterest_site_verification: s("pinterest_site_verification"),
      turnstile_site_key:       s("turnstile_site_key"),
      turnstile_secret_key:     s("turnstile_secret_key"),
      showcaptcha:              b("showcaptcha"),
      captcha_site_key:         s("captcha_site_key"),
      captcha_site_secret:      s("captcha_site_secret"),
      algolia_instant_search:   b("algolia_instant_search"),
      algolia_autocomplete:     b("algolia_autocomplete"),
      algolia_app_id:           s("algolia_app_id"),
      algolia_search_key:       s("algolia_search_key"),
      algolia_verification:     s("algolia_verification"),
      algolia_product_index:    s("algolia_product_index"),
      algolia_category_index:   s("algolia_category_index"),
      algolia_article_index:    s("algolia_article_index"),
      algolia_suggestion_index: s("algolia_suggestion_index"),
      inv_level:                s("inv_level"),
      show_in_stock:            b("show_in_stock"),
      out_of_stock:             b("out_of_stock"),
      show_retail:              b("show_retail"),
      order_button_text:        s("order_button_text"),
      alert_display:            b("alert_display"),
      alert_message:            raw("alert_message"),
    }
  );
}
